# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: "Upload Release Assets"
description: "Github Action for uploading assets to existing releases"
author: "Brian Pickens and contributors"
inputs:
  release_id:
    description: "The release_id of the release to update"
    required: true
  files:
    description: "Newline-delimited list of path globs for asset files to upload"
    required: true
  fail_on_unmatched_files:
    description: "Fails if any of the `files` globs match nothing. Defaults to false"
    required: true
  token:
    description: "Authorized secret GitHub Personal Access Token. Defaults to github.token"
    required: false
    default: ${{ github.token }}
env:
  "GITHUB_TOKEN": "As provided by Github Actions"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "package"